[package]
name = "tldr-lib"
description = "Tang protocol library implementation"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Thomas Johnson <NTmatter@gmail.com>", "Martyn P <martyn@datasync.dev>"]
repository = "https://github.com/NTmatter/tldr-lib"

[dependencies]
p521 = { version = ">=0.13.3", features = ["ecdh", "ecdsa", "jwk"] }
elliptic-curve = { version = "0.13.8", features = ["jwk"] }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
base64ct = "1.6"
sha2 = "0.10"
url = { version = "2.5.4", features = ["serde"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }

aws-config = { version = "1.5.15", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.62.0"
anyhow = "1.0.95"

[dev-dependencies]
tempdir = "0.3.7"
